version: "3.3"
services:
  master: 
    image: dvemuri/dist_fog_comp:distML-lnx
    ports:
      - "2550:2550"
    volumes:
      - /home/deepika/eclipse-workspace5/pi-akka-sharding/lib/datasets/iris_train.csv:/root/datasets/train.csv
      - /home/deepika/eclipse-workspace5/pi-akka-sharding/lib/datasets/iris_test.csv:/root/datasets/test.csv
    environment:
      CLUSTER_PORT: 2550
      CLUSTER_IP: master
      SEED1_IP: worker1
      SEED2_IP: worker2
      ROLE: master
    
    deploy:
      replicas: 1      
      placement:
        constraints: [node.hostname == deepika-Lenovo-Z51-70]
    command: ["java","-jar","/app.jar", "master", "2550"]

  worker1: 
    image: dvemuri/dist_fog_comp:distML-lnx
    ports:
      - "2552:2552"
    environment:
      CLUSTER_PORT: 2552
      CLUSTER_IP: worker1
      SEED1_IP: worker1
      SEED2_IP: worker2
      ROLE: worker

    deploy:
      replicas: 1      
      placement:
        constraints: [node.hostname == raspi1]
    command: ["java","-jar","/app.jar", "worker", "2552"]

  worker2: 
    image: dvemuri/dist_fog_comp:distML-lnx
    ports:
      - "2534:2534"
    environment:
      CLUSTER_PORT: 2534
      CLUSTER_IP: worker2
      SEED1_IP: worker1
      SEED2_IP: worker2
      ROLE: worker
      
    deploy:
      replicas: 1      
      placement:
        constraints: [node.hostname == raspi3]
    command: ["java","-jar","/app.jar", "worker", "2534"]

  worker3: 
    image: dvemuri/dist_fog_comp:distML-lnx
    ports:
      - "2553:2553"
    environment:
      CLUSTER_PORT: 2553
      CLUSTER_IP: worker3
      SEED1_IP: worker1
      SEED2_IP: worker2
      ROLE: worker
      
    deploy:
      replicas: 1      
      placement:
        constraints: [node.hostname == raspi4]
    command: ["java","-jar","/app.jar", "worker", "2553"]